### PR TITLE
Added upper limits for ChangesRelogInterval.

### PR DESCRIPTION
**Pull request by Marc-Berg**
Fixes issue https://github.com/ioBroker/ioBroker.influxdb/issues/324

### CODE REVIEW

**Comment by Marc-Berg** [comment]
> Also in the code we should check it

To catch the users who have already set the value incorrectly, or what use case is this intended to address?

**Comment by Apollon77** [comment]
Exactly. to catch this or users that use too old admion versions maybe and so could bypass these UI checks. Better safe :-)

**Comment by Apollon77** [comment]
hm ... closed because? ;-)

**Comment by Marc-Berg** [comment]
I will create a new PR with both changes to the config and the code.

**Pull request closed without merging**
