### PR TITLE
Influx 2: Fix retention policy handling, fix db cleanup

### PR DESCRIPTION
**Pull request by Excodibur**
- fixed Retention policy updates
- fixed Iflx2 DB reset/cleanup,
- minor GUI fixes

### CODE REVIEW

**Comment by Excodibur** [comment]
Addresses issues:

- https://github.com/ioBroker/ioBroker.influxdb/issues/119
- https://github.com/ioBroker/ioBroker.influxdb/issues/29

**Comment by Sineos** [comment]
Any updates? Eagerly waiting for Influxdb 2 😇

**Comment by Apollon77** [comment]
will review tomorrow. too tired

**Comment by Apollon77** [comment]
@Excodibur In general code looks good.
I also expected that you remove retention setting from "custom" (config and code... ?! Because we do mot support that anymore

What happens if a user changes a retention policy to a "lower" value? WIll InfluxDB delete all data directly? Then we should check that and not do such achange without user setting a special flag in admin or such ...

**Comment by Excodibur** [comment]
@Apollon77 Thanks for the remarks.

T.b.h. I am not really familiar with the logic/dependencies behind the "custom" part. Perhaps you can advise me what parts can be deleted. :-)

Your second question is a bit difficult to answer without more information about the scenario. In general you cannot set retention periods lower than one hour, so nothing should be deleted right away. But if you change the retention period to a smaller value than before, you potentially can lose some of that old data during the next cleanup. But it also depends on other factors like Shard Duration, etc.

I started writing a separate doc [Understanding Retention Policies](RetentionPolicies.md) for it, so we can write down a common view there.

**Comment by Apollon77** [comment]
For removing retention ...
* https://github.com/ioBroker/ioBroker.influxdb/blob/master/admin/custom_m.html#L35-L48 that part and equivalent in jsonconfig
* same for https://github.com/ioBroker/ioBroker.influxdb/blob/master/main.js#L101-L105 and https://github.com/ioBroker/ioBroker.influxdb/blob/master/main.js#L124-L127and https://github.com/ioBroker/ioBroker.influxdb/blob/master/main.js#L577-L581 and https://github.com/ioBroker/ioBroker.influxdb/blob/master/main.js#L603-L606

And so for the retention to be sure I would do
* if someone set a new retention which is "longer" then we do it
* if someone lowers the retention we offer a checkbox with "yes really set the lower retention" and omly if this is set we do it, else we log "can not do, please tick the checkbox" ... We need to protect users from doing damaging stuff ... 
What do you think?

**Pull request merged**
