### PR TITLE
getHistory: Interpolation fix for first and last values, if they are beyond of requested time-range 

### PR DESCRIPTION
**Pull request by PeterVoronov**
New PR to be align with current updates in the code.
More details in https://github.com/ioBroker/ioBroker.influxdb/pull/206

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you! 
Please wait with the next implementations. I will try to debug this case.
Your solution is OK, but some of the corner conditions are not checked, (e.g. start=end or null values)

**Comment by PeterVoronov** [comment]
> Thank you! Please wait with the next implementations. I will try to debug this case. Your solution is OK, but some of the corner conditions are not checked, (e.g. start=end or null values)

Thanks.
start=end already excluded, when the count of items is more then 2 (i.e. start, one inside, end).
For the null values - it's important, will look on it

**Comment by Apollon77** [comment]
@GermanBluefox @PeterVoronov Is that PR still relevant after the work @GermanBluefox did in 1.5.x?

**Comment by PeterVoronov** [comment]
> @GermanBluefox @PeterVoronov Is that PR still relevant after the work @GermanBluefox did in 1.5.x?

the same logic is implemented in other way by @GermanBluefox , so, we can close it.
Many thanks

**Pull request closed without merging**
