### PR TITLE
Adding 5 years option to retention period

### PR DESCRIPTION
**Pull request by Flyor**
In my case, 2 years are not enough, but forever will be too much. So I added a 5 years rentetion period.

### CODE REVIEW

**Comment by Apollon77** [comment]
Thatnk you for your contribution. The new version on GitHub (3.0.0) has the new option to define a cistom retention period in "days" ... This should be sufiicient for your case too, or?

**Comment by Flyor** [comment]
> Thatnk you for your contribution. The new version on GitHub (3.0.0) has the new option to define a cistom retention period in "days" ... This should be sufiicient for your case too, or?

For sure - that will be enough if the maximum days could be above 2years. Will the other adapters (e.g. history) get the same options?

**Comment by Apollon77** [comment]
Number of days for custom is kind of not limited. And yes GitHub versions of sql and hstory (all big major updates like influxdb) will have the same option to be in sync ... See also the Tester threads in Forum for all three adapters.

Then I would close this PR

**Comment by Apollon77** [comment]
PS: You're welcome to test the GitHub version :-)

**Pull request closed without merging**
