### PR TITLE
Expose flush buffer

### PR DESCRIPTION
**Pull request by lvogt**
This allows other adapters to instruct the influx adapter to write the cached values to disk. 
Otherwise queries to db will not contain cached values.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hm ... I need to look into this ... On one hand someone that uses buffered write shopuld be aware of this. When you will call this method? You do which calls to query where?

Also the "already planned" and such I'm not sure if this is that clean and the "beware" comment is a limiting i'm not sure about ... will think about it

**Comment by lvogt** [comment]
I execute queries from another adapter via "query" messages and therefore just emit a "flush" message beforehand.

Just to be sure: As far as I read into the source, currently all queries (both, a custom "query" and getHistory() calls) to db simply ignore buffered data, correct?

The "beware hint" is there mostly, because the current implementation for writeAllSeriesPerID() *might* execute the callback before all asynchronous calls to client.writePoints have completed - at least as far as I interpretated the source code.

I have to agree the case where seriesBufferFlushPlanned is already true is "unclean" - but I am unsure how to deal with it... I could check in intervals for seriesBufferCounter to change to 0, but this might also end up in a race condition where the counter is reset and new data buffered before the check has completed...

**Comment by Apollon77** [comment]
Yes all queries go to DB and so ignoring buffered queries ... it would be too much effort to combine that and also do calculations of the buffered data. Will never be 100% in sync
In my case I use a 1000 buffer and it writes every 2 mins in my prod system ... so I personally would be ok with "ignoring " those data but in fact this is the question of the usecase ;-)

I need to re-think-into the whole topic, maybe I then find  a better way

**Comment by Apollon77** [comment]
If this is really needed now needs to be redone because of the bifg changes in 2.x, sorry

**Comment by Apollon77** [comment]
PS: WIll be in 3.0

**Pull request closed without merging**
