### PR TITLE
Improve getHistory query if using Influx-V2

### PR DESCRIPTION
**Pull request by mango1402**
solves issue https://github.com/ioBroker/ioBroker.influxdb/issues/328

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Are you sure, that 
`|> sort(columns: ["_time"], desc: true) `
not required?

**Comment by Marc-Berg** [comment]
> Are you sure, that `group() ` not required?

Also from my point of view these two queries are equivalent.

**Comment by mango1402** [comment]
if requesting just one row - done by using first() or last() - there is no need to sort or group.....

**Comment by Apollon77** [comment]
Cool, thank you, @GermanBluefox and also myself are not using InfluxDB 2.x so we were unsure. I will merge soon!

**Pull request merged**
