### PR TITLE
Small fix for the getHistory/getHistoryIflx2 to decrease possible time difference for first and last items from the desired interval borders

### PR DESCRIPTION
**Pull request by PeterVoronov**
Currently in this adapter in functions getHistory/getHistoryIflx2 the history data is requested from database  not only inside of the time interval, received by getHistory request, but, for "smooth" drawing, one value before and one after in the appropriate timeseries...
But, in some cases, the timestamp of this "additional" data-points can be significantly differ from begin and end values(borders) of requested time interval... Up to several days ...
To avoid it the time stamp of this data-points will be manually set as much close to the "borders" as possible. In proposed PR it is equal to 1 second.

### CODE REVIEW

**Comment by PeterVoronov** [comment]
It have to close the appropriate [issue ](https://github.com/ioBroker/ioBroker.influxdb/issues/207).

**Comment by PeterVoronov** [comment]
> This pull request **introduces 2 alerts** when merging [587b1b0](https://github.com/ioBroker/ioBroker.influxdb/commit/587b1b040596cfc4784c2bb0a3a017d9b4a41b05) into [111fcd1](https://github.com/ioBroker/ioBroker.influxdb/commit/111fcd14be2471c0dd658ae5558e92314b65afaa) - [view on LGTM.com](https://lgtm.com/projects/g/ioBroker/ioBroker.influxdb/rev/pr-090dfa426ea075af4891ea2fcb6676d151e613d2)
> 
> **new alerts:**
> 
> * 2 for Unused variable, import, function or class

Fixed ;-)

**Comment by GermanBluefox** [comment]
Your solution falsifies the data:
image

**Comment by PeterVoronov** [comment]
> Your solution falsifies the data: image

As discussed in the Telegram - Implemented the linear data interpolation, to provide less fake data.

**Pull request closed without merging**
